// Database types generated from Supabase schema
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type UserRole = 'student' | 'lecturer' | 'admin';
export type ApplicationStatus = 'pending' | 'approved' | 'rejected';
export type TournamentStatus = 'draft' | 'registration' | 'ongoing' | 'completed' | 'cancelled';
export type BracketType = 'single_elimination' | 'double_elimination' | 'round_robin' | 'group_stage';
export type MatchStatus = 'scheduled' | 'ongoing' | 'completed' | 'cancelled';
export type TeamRole = 'captain' | 'member';

export interface Database {
  public: {
    Tables: {
      institutions: {
        Row: {
          id: string;
          name: string;
          slug: string;
          type: string;
          address: string | null;
          city: string | null;
          state: string | null;
          logo_url: string | null;
          banner_url: string | null;
          primary_color: string;
          secondary_color: string;
          description: string | null;
          website_url: string | null;
          contact_email: string | null;
          contact_phone: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          type: string;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          logo_url?: string | null;
          banner_url?: string | null;
          primary_color?: string;
          secondary_color?: string;
          description?: string | null;
          website_url?: string | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          type?: string;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          logo_url?: string | null;
          banner_url?: string | null;
          primary_color?: string;
          secondary_color?: string;
          description?: string | null;
          website_url?: string | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      users: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          username: string | null;
          role: UserRole;
          institution_id: string | null;
          avatar_url: string | null;
          phone_number: string | null;
          bio: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name: string;
          username?: string | null;
          role?: UserRole;
          institution_id?: string | null;
          avatar_url?: string | null;
          phone_number?: string | null;
          bio?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          username?: string | null;
          role?: UserRole;
          institution_id?: string | null;
          avatar_url?: string | null;
          phone_number?: string | null;
          bio?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      lecturer_applications: {
        Row: {
          id: string;
          user_id: string;
          full_name: string;
          institution_id: string;
          phone_number: string;
          staff_id: string | null;
          department: string | null;
          supporting_document_url: string | null;
          reason: string | null;
          status: ApplicationStatus;
          reviewed_by: string | null;
          reviewed_at: string | null;
          rejection_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          full_name: string;
          institution_id: string;
          phone_number: string;
          staff_id?: string | null;
          department?: string | null;
          supporting_document_url?: string | null;
          reason?: string | null;
          status?: ApplicationStatus;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          rejection_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          full_name?: string;
          institution_id?: string;
          phone_number?: string;
          staff_id?: string | null;
          department?: string | null;
          supporting_document_url?: string | null;
          reason?: string | null;
          status?: ApplicationStatus;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          rejection_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      tournaments: {
        Row: {
          id: string;
          title: string;
          slug: string;
          description: string | null;
          game_category: string;
          banner_url: string | null;
          logo_url: string | null;
          organizer_id: string;
          institution_id: string | null;
          bracket_type: BracketType;
          max_teams: number;
          team_size: number;
          registration_start: string;
          registration_end: string;
          tournament_start: string;
          tournament_end: string | null;
          status: TournamentStatus;
          prize_pool: number | null;
          prize_currency: string;
          prize_description: string | null;
          rules: string | null;
          requirements: string | null;
          primary_color: string | null;
          secondary_color: string | null;
          is_featured: boolean;
          view_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          description?: string | null;
          game_category: string;
          banner_url?: string | null;
          logo_url?: string | null;
          organizer_id: string;
          institution_id?: string | null;
          bracket_type?: BracketType;
          max_teams?: number;
          team_size?: number;
          registration_start: string;
          registration_end: string;
          tournament_start: string;
          tournament_end?: string | null;
          status?: TournamentStatus;
          prize_pool?: number | null;
          prize_currency?: string;
          prize_description?: string | null;
          rules?: string | null;
          requirements?: string | null;
          primary_color?: string | null;
          secondary_color?: string | null;
          is_featured?: boolean;
          view_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          description?: string | null;
          game_category?: string;
          banner_url?: string | null;
          logo_url?: string | null;
          organizer_id?: string;
          institution_id?: string | null;
          bracket_type?: BracketType;
          max_teams?: number;
          team_size?: number;
          registration_start?: string;
          registration_end?: string;
          tournament_start?: string;
          tournament_end?: string | null;
          status?: TournamentStatus;
          prize_pool?: number | null;
          prize_currency?: string;
          prize_description?: string | null;
          rules?: string | null;
          requirements?: string | null;
          primary_color?: string | null;
          secondary_color?: string | null;
          is_featured?: boolean;
          view_count?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      teams: {
        Row: {
          id: string;
          name: string;
          slug: string;
          tag: string | null;
          logo_url: string | null;
          banner_url: string | null;
          institution_id: string | null;
          captain_id: string;
          is_recruiting: boolean;
          max_members: number;
          description: string | null;
          social_links: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          tag?: string | null;
          logo_url?: string | null;
          banner_url?: string | null;
          institution_id?: string | null;
          captain_id: string;
          is_recruiting?: boolean;
          max_members?: number;
          description?: string | null;
          social_links?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          tag?: string | null;
          logo_url?: string | null;
          banner_url?: string | null;
          institution_id?: string | null;
          captain_id?: string;
          is_recruiting?: boolean;
          max_members?: number;
          description?: string | null;
          social_links?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      team_members: {
        Row: {
          id: string;
          team_id: string;
          user_id: string;
          role: TeamRole;
          in_game_name: string | null;
          in_game_id: string | null;
          position: string | null;
          joined_at: string;
        };
        Insert: {
          id?: string;
          team_id: string;
          user_id: string;
          role?: TeamRole;
          in_game_name?: string | null;
          in_game_id?: string | null;
          position?: string | null;
          joined_at?: string;
        };
        Update: {
          id?: string;
          team_id?: string;
          user_id?: string;
          role?: TeamRole;
          in_game_name?: string | null;
          in_game_id?: string | null;
          position?: string | null;
          joined_at?: string;
        };
      };
      tournament_participants: {
        Row: {
          id: string;
          tournament_id: string;
          team_id: string;
          registered_by: string;
          registered_at: string;
          is_approved: boolean;
          is_checked_in: boolean;
          checked_in_at: string | null;
          seed_number: number | null;
          wins: number;
          losses: number;
          points: number;
        };
        Insert: {
          id?: string;
          tournament_id: string;
          team_id: string;
          registered_by: string;
          registered_at?: string;
          is_approved?: boolean;
          is_checked_in?: boolean;
          checked_in_at?: string | null;
          seed_number?: number | null;
          wins?: number;
          losses?: number;
          points?: number;
        };
        Update: {
          id?: string;
          tournament_id?: string;
          team_id?: string;
          registered_by?: string;
          registered_at?: string;
          is_approved?: boolean;
          is_checked_in?: boolean;
          checked_in_at?: string | null;
          seed_number?: number | null;
          wins?: number;
          losses?: number;
          points?: number;
        };
      };
      matches: {
        Row: {
          id: string;
          tournament_id: string;
          round: number;
          match_number: number;
          best_of: number;
          team1_id: string | null;
          team2_id: string | null;
          winner_id: string | null;
          team1_score: number;
          team2_score: number;
          status: MatchStatus;
          scheduled_at: string | null;
          started_at: string | null;
          completed_at: string | null;
          next_match_id: string | null;
          losers_match_id: string | null;
          notes: string | null;
          stream_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tournament_id: string;
          round: number;
          match_number: number;
          best_of?: number;
          team1_id?: string | null;
          team2_id?: string | null;
          winner_id?: string | null;
          team1_score?: number;
          team2_score?: number;
          status?: MatchStatus;
          scheduled_at?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          next_match_id?: string | null;
          losers_match_id?: string | null;
          notes?: string | null;
          stream_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tournament_id?: string;
          round?: number;
          match_number?: number;
          best_of?: number;
          team1_id?: string | null;
          team2_id?: string | null;
          winner_id?: string | null;
          team1_score?: number;
          team2_score?: number;
          status?: MatchStatus;
          scheduled_at?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          next_match_id?: string | null;
          losers_match_id?: string | null;
          notes?: string | null;
          stream_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      match_games: {
        Row: {
          id: string;
          match_id: string;
          game_number: number;
          winner_id: string | null;
          team1_score: number | null;
          team2_score: number | null;
          game_data: Json | null;
          screenshot_url: string | null;
          video_url: string | null;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          match_id: string;
          game_number: number;
          winner_id?: string | null;
          team1_score?: number | null;
          team2_score?: number | null;
          game_data?: Json | null;
          screenshot_url?: string | null;
          video_url?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          match_id?: string;
          game_number?: number;
          winner_id?: string | null;
          team1_score?: number | null;
          team2_score?: number | null;
          game_data?: Json | null;
          screenshot_url?: string | null;
          video_url?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
      };
    };
  };
}
